import { useState } from 'react';
import { ActivityIndicator, Image, KeyboardAvoidingView, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Link } from 'expo-router';
import { useAuth } from '@/components/AuthProvider';
const C={bg:'#000000',card:'#151515',input:'#0B0B0B',border:'#303030',text:'#FFFFFF',muted:'#A7A7A7',placeholder:'#777777',error:'#FF7777',success:'#70D39A',button:'#252525',buttonBorder:'#333333'};
export default function ForgotPasswordScreen(){
 const {sendPasswordReset,loading}=useAuth(); const [email,setEmail]=useState(''); const [error,setError]=useState<string|null>(null); const [sent,setSent]=useState(false);
 const send=async()=>{const e=email.trim().toLowerCase();if(!e){setError('Please enter your email address.');return;}setError(null);setSent(false);const r=await sendPasswordReset(e);if(r.error){setError(r.error);return;}setSent(true)};
 return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==='ios'?'padding':'height'}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.card}>
  <Image source={require('@/assets/sidekick.png')} style={s.logo}/><Text style={s.title}>Reset your password</Text><Text style={s.sub}>Enter your email and we'll send you a secure password reset link.</Text>
  {sent?<View style={s.successBox}><Text style={s.success}>Password reset email sent. If this account exists, check your inbox and tap the link.</Text></View>:null}
  {error?<View style={s.errorBox}><Text style={s.error}>{error}</Text></View>:null}
  <Text style={s.label}>Email</Text><TextInput value={email} onChangeText={v=>{setEmail(v);setError(null);setSent(false)}} autoCapitalize="none" autoCorrect={false} keyboardType="email-address" autoComplete="email" placeholder="you@example.com" placeholderTextColor={C.placeholder} style={s.input}/>
  <Pressable onPress={send} disabled={loading} style={[s.primary,loading&&s.disabled]}>{loading?<ActivityIndicator color="#FFFFFF"/>:<Text style={s.primaryText}>Send reset link</Text>}</Pressable>
  <Link href="/login" asChild><Pressable style={s.back}><Text style={s.backText}>Back to Sign In</Text></Pressable></Link>
 </View></ScrollView></KeyboardAvoidingView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},flex:{flex:1},content:{flexGrow:1,justifyContent:'center',alignItems:'center',padding:18},card:{width:'100%',maxWidth:430,backgroundColor:C.card,borderRadius:30,borderWidth:1,borderColor:'#242424',padding:28},logo:{width:92,height:92,borderRadius:46,alignSelf:'center',marginBottom:20},title:{color:C.text,fontFamily:'Poppins-Bold',fontSize:22,textAlign:'center'},sub:{color:C.muted,fontFamily:'Poppins-Regular',fontSize:12,lineHeight:18,marginTop:6,marginBottom:24,textAlign:'center'},label:{color:C.text,fontFamily:'Poppins-Medium',fontSize:11.5,marginBottom:7,marginLeft:3},input:{width:'100%',minHeight:52,backgroundColor:C.input,borderWidth:1,borderColor:C.border,borderRadius:15,paddingHorizontal:15,color:C.text,fontFamily:'Poppins-Regular',fontSize:13},primary:{minHeight:52,borderRadius:15,backgroundColor:C.button,borderWidth:1,borderColor:C.buttonBorder,alignItems:'center',justifyContent:'center',marginTop:18},primaryText:{color:C.text,fontFamily:'Poppins-Bold',fontSize:12.5},back:{alignItems:'center',paddingVertical:12},backText:{color:C.muted,fontFamily:'Poppins-SemiBold',fontSize:11.5},errorBox:{backgroundColor:'#241414',borderWidth:1,borderColor:'#492323',borderRadius:13,padding:11,marginBottom:15},error:{color:C.error,fontFamily:'Poppins-Regular',fontSize:11.5,lineHeight:17,textAlign:'center'},successBox:{backgroundColor:'#102219',borderWidth:1,borderColor:'#245437',borderRadius:13,padding:11,marginBottom:15},success:{color:C.success,fontFamily:'Poppins-Regular',fontSize:11.5,lineHeight:17,textAlign:'center'},disabled:{opacity:.55}});
