import { useState } from 'react';
import { ActivityIndicator, Image, KeyboardAvoidingView, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { Eye, EyeOff } from 'lucide-react-native';
import { useAuth } from '@/components/AuthProvider';
const C={bg:'#000000',card:'#151515',input:'#0B0B0B',border:'#303030',text:'#FFFFFF',muted:'#A7A7A7',placeholder:'#777777',error:'#FF7777',success:'#70D39A',button:'#252525',buttonBorder:'#333333'};
export default function ResetPasswordScreen(){
 const {updatePassword,loading}=useAuth();const[p,setP]=useState('');const[c,setC]=useState('');const[show,setShow]=useState(false);const[showC,setShowC]=useState(false);const[error,setError]=useState<string|null>(null);const[done,setDone]=useState(false);
 const valid=p.length>=6&&/[A-Za-z]/.test(p)&&/[0-9]/.test(p)&&/[^A-Za-z0-9]/.test(p);
 const save=async()=>{setError(null);if(!valid){setError('Password must be at least 6 characters and contain a letter, number, and special character.');return;}if(p!==c){setError('Passwords do not match.');return;}const r=await updatePassword(p);if(r.error){setError(r.error);return;}setDone(true)};
 if(done)return <SafeAreaView style={s.safe}><View style={s.center}><View style={s.card}><Image source={require('@/assets/sidekick.png')} style={s.logo}/><Text style={s.title}>Password updated</Text><Text style={s.sub}>Your password has been changed successfully.</Text><Pressable onPress={()=>router.replace('/login' as never)} style={s.primary}><Text style={s.primaryText}>Back to Sign In</Text></Pressable></View></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==='ios'?'padding':'height'}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.card}>
 <Image source={require('@/assets/sidekick.png')} style={s.logo}/><Text style={s.title}>Create a new password</Text><Text style={s.sub}>Choose a new password for your My Sidekick account.</Text>
 {error?<View style={s.errorBox}><Text style={s.error}>{error}</Text></View>:null}
 <Text style={s.label}>New Password</Text><View style={s.wrap}><TextInput value={p} onChangeText={v=>{setP(v);setError(null)}} secureTextEntry={!show} autoCapitalize="none" autoCorrect={false} autoComplete="new-password" placeholder="New password" placeholderTextColor={C.placeholder} style={[s.input,s.password]}/><Pressable onPress={()=>setShow(v=>!v)} style={s.eye}>{show?<EyeOff size={19} color={C.muted}/>:<Eye size={19} color={C.muted}/>}</Pressable></View>
 <View style={s.req}><Text style={/[A-Za-z]/.test(p)?s.met:s.unmet}>{/[A-Za-z]/.test(p)?'✓':'×'} At least 1 letter</Text><Text style={/[0-9]/.test(p)?s.met:s.unmet}>{/[0-9]/.test(p)?'✓':'×'} At least 1 number</Text><Text style={/[^A-Za-z0-9]/.test(p)?s.met:s.unmet}>{/[^A-Za-z0-9]/.test(p)?'✓':'×'} At least 1 special character</Text><Text style={p.length>=6?s.met:s.unmet}>{p.length>=6?'✓':'×'} At least 6 characters</Text></View>
 <Text style={s.confirmLabel}>Confirm Password</Text><View style={s.wrap}><TextInput value={c} onChangeText={setC} secureTextEntry={!showC} autoCapitalize="none" autoCorrect={false} autoComplete="new-password" placeholder="Confirm password" placeholderTextColor={C.placeholder} style={[s.input,s.password]}/><Pressable onPress={()=>setShowC(v=>!v)} style={s.eye}>{showC?<EyeOff size={19} color={C.muted}/>:<Eye size={19} color={C.muted}/>}</Pressable></View>
 <Pressable onPress={save} disabled={loading} style={[s.primary,loading&&s.disabled]}>{loading?<ActivityIndicator color="#FFFFFF"/>:<Text style={s.primaryText}>Update Password</Text>}</Pressable>
 </View></ScrollView></KeyboardAvoidingView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},flex:{flex:1},center:{flex:1,justifyContent:'center',alignItems:'center',padding:18},content:{flexGrow:1,justifyContent:'center',alignItems:'center',padding:18},card:{width:'100%',maxWidth:430,backgroundColor:C.card,borderRadius:30,borderWidth:1,borderColor:'#242424',padding:28},logo:{width:92,height:92,borderRadius:46,alignSelf:'center',marginBottom:20},title:{color:C.text,fontFamily:'Poppins-Bold',fontSize:22,textAlign:'center'},sub:{color:C.muted,fontFamily:'Poppins-Regular',fontSize:12,lineHeight:18,marginTop:6,marginBottom:24,textAlign:'center'},label:{color:C.text,fontFamily:'Poppins-Medium',fontSize:11.5,marginBottom:7,marginLeft:3},input:{width:'100%',minHeight:52,backgroundColor:C.input,borderWidth:1,borderColor:C.border,borderRadius:15,paddingHorizontal:15,color:C.text,fontFamily:'Poppins-Regular',fontSize:13},wrap:{position:'relative'},password:{paddingRight:50},eye:{position:'absolute',right:14,top:0,bottom:0,width:28,alignItems:'center',justifyContent:'center'},req:{marginTop:8,gap:4},met:{color:C.success,fontFamily:'Poppins-Regular',fontSize:10.5},unmet:{color:C.error,fontFamily:'Poppins-Regular',fontSize:10.5},confirmLabel:{color:C.text,fontFamily:'Poppins-Medium',fontSize:11.5,marginTop:18,marginBottom:7},primary:{minHeight:52,borderRadius:15,backgroundColor:C.button,borderWidth:1,borderColor:C.buttonBorder,alignItems:'center',justifyContent:'center',marginTop:22},primaryText:{color:C.text,fontFamily:'Poppins-Bold',fontSize:12.5},errorBox:{backgroundColor:'#241414',borderWidth:1,borderColor:'#492323',borderRadius:13,padding:11,marginBottom:15},error:{color:C.error,fontFamily:'Poppins-Regular',fontSize:11.5,lineHeight:17,textAlign:'center'},disabled:{opacity:.55}});
