# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE will override
# any settings specified in this file.

# Gradle JVM
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

# Parallel Gradle builds
org.gradle.parallel=true

# AndroidX
android.useAndroidX=true

# AAPT2 PNG crunching
android.enablePngCrunchInReleaseBuilds=true

# React Native architectures
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# React Native new architecture
newArchEnabled=true

# Hermes JavaScript engine
hermesEnabled=true

# Edge-to-edge display
edgeToEdgeEnabled=true

# Expo image support
expo.gif.enabled=true
expo.webp.enabled=true
expo.webp.animated=false

# Network inspector
EX_DEV_CLIENT_NETWORK_INSPECTOR=true

# Expo packaging
expo.useLegacyPackaging=false

# Expo edge-to-edge
expo.edgeToEdgeEnabled=true


# ============================================================
# ANDROID RELEASE SIGNING
# ============================================================
# These values are for the existing EAS production keystore.
# DO NOT share the two passwords.

MYAPP_UPLOAD_STORE_FILE=C:/sidekick/project/@mysidekick__bolt-expo-nativewind.jks
MYAPP_UPLOAD_KEY_ALIAS=865ea6849a1e96c4740975b8f548ea14
MYAPP_UPLOAD_STORE_PASSWORD=043cee21ebfe0b2912e39ac138a877da
MYAPP_UPLOAD_KEY_PASSWORD=cb1ea5fa0412741cc84a109a40b8bbf9